seed: 17
data:
  name: sleepwalker.datasets.HSP.HSP
  channels:
    - logical_name: EEG
      physical_names: [C3-M2, C4-M1, F3-M2, F4-M1, O1-M2, O2-M1, CZ-M2, CZ-M1, C3-M1, C4-M2, F3-M1, F4-M2, O1-M1, O2-M2]
      normalizer: 
        name: sleepwalker.datasets.normalizer.EEGFilterNormalizer.EEGFilterNormalizer
        fs: 100
      unit: uV
    - logical_name: EOG
      physical_names: [E1-M2, E2-M1, E2-M2, E1, E2, Eye Up, Eye Down]
      normalizer: 
        name: sleepwalker.datasets.normalizer.EEGFilterNormalizer.EEGFilterNormalizer
        fs: 100
      unit: uV
    - logical_name: Chin EMG
      physical_names: [CHIN1-CHIN2, Chin1-Chin2, CHIN1-CHIN3, Chin1-Chin3, CHIN2-CHIN3, Chin2-Chin3, Chin3-Chin2, Chin3, Chin2, CHIN1, CHIN2, CHIN3, CHIN, CHINz, EMG]
      unit: uV
    - logical_name: Abdomen
      physical_names: [ABD, ABDOMEN, Abdomen]
      normalizer: 
        name: sleepwalker.datasets.normalizer.RespirationFilterNormalizer.RespirationFilterNormalizer
        fs: 100
      unit: uV
    - logical_name: Chest
      physical_names: [CHEST, THORAX, Chest]
      normalizer: 
        name: sleepwalker.datasets.normalizer.RespirationFilterNormalizer.RespirationFilterNormalizer
        fs: 100
      unit: uV
    - logical_name: Airflow
      physical_names: [PTAF, AIRFLOW, AirFlow, Airflow2, IC, THERMISTOR, Thermistor, Flow, Flow_DR, CFLOW, CFlow, C-Flow, XFlow]
      normalizer: 
        name: sleepwalker.datasets.normalizer.RespirationFilterNormalizer.RespirationFilterNormalizer
        fs: 100
      unit: uV
    - logical_name: SpO2
      physical_names: [SaO2, SpO2, SPO2]
      normalizer:
        name: sleepwalker.datasets.normalizer.SaturationFilterNormalizer.SaturationFilterNormalizer
        fs: 100
      unit: '%'
  sample_frequency: 100
  event_mapping:
    wake: wake
    n1: n1
    n2: n2
    n3: n3
    rem: rem
    arousal: arousal
    apnea: apnea
    obstructive-apnea: apnea
    mixed-apnea: apnea
    central-apnea: apnea
    hypopnea: hypopnea
    desaturation: desaturation
  remove_unmapped_events: true
  total_input: 630s
  target_resolution: 30s
  stride: 30s
  prepare_patient:
    name: sleepwalker.training.callbacks.trim_patient_to_events
    keep_events: [wake, n1, n2, n3, rem]
  prepare_target:
    name: sleepwalker.trainer.MultiLabelTrainer.MultiLabelTrainer.prepare_target
    task_config:
      name: sleepwalker.trainer.MultiLabelTrainer.MultiLabelTrainer.normalize_task_config
      task_config:
        sleep:
          labels: [wake, n1, n2, n3, rem]
          default: null
          target_resolution: 30s
          loss_function: torch.nn.functional.cross_entropy
          loss_mode: inverse-log
        arousal:
          labels: [arousal, no arousal]
          default: no arousal
          target_resolution: 1s
          loss_function: torch.nn.functional.cross_entropy
          loss_mode: inverse-log
        breathing:
          labels: [apnea, hypopnea, regular breathing]
          default: regular breathing
          target_resolution: 5s
          loss_function: torch.nn.functional.cross_entropy
          loss_mode: inverse-log
        desaturation:
          labels: [desaturation, no desaturation]
          default: no desaturation
          target_resolution: 10s
          loss_function: torch.nn.functional.cross_entropy
          loss_mode: inverse-log
  prepare_sample:
    name: sleepwalker.training.callbacks.tensor_sample
    max_nan_fraction: 0
  files: results/hsp_expert_suite/full/hsp_split.yml
  label: HSP
  num_workers: 8
model:
  name: sleepwalker.models.MetaModel.MetaModel
  task_config:
    name: sleepwalker.trainer.MultiLabelTrainer.MultiLabelTrainer.normalize_task_config
    task_config:
      sleep:
        labels: [wake, n1, n2, n3, rem]
        default: null
        target_resolution: 30s
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse-log
      arousal:
        labels: [arousal, no arousal]
        default: no arousal
        target_resolution: 1s
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse-log
      breathing:
        labels: [apnea, hypopnea, regular breathing]
        default: regular breathing
        target_resolution: 5s
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse-log
      desaturation:
        labels: [desaturation, no desaturation]
        default: no desaturation
        target_resolution: 10s
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse-log
  models:
    - name: sleepwalker.models.MultiModel.MetaModelEntry
      input_channels: [EEG]
      model:
        name: sleepwalker.models.SleepTransformer.SleepTransformer
        classes: null
        epoch_seq_len: 21
    - name: sleepwalker.models.MultiModel.MetaModelEntry
      input_channels: [EOG, Chin EMG, Abdomen, Chest, Airflow, SpO2]
      model:
        name: sleepwalker.models.UTime.UTime
        classes: null
        sampling_frequency: 0.01s
        channel: [96, 192, 192, 384]
        maxpool: [10, 8, 6, 4]
        kernel: [5, 5, 5, 5]
        norm: channel
        mlp_size: 512
        activation: elu
        dropout_p: 0
trainer:
  name: sleepwalker.trainer.MultiLabelTrainer.MultiLabelTrainer
  epochs: 30
  optimizer:
    name: torch.optim.AdamW
    lr: 0.0003
    weight_decay: 0.0001
  task_config:
    name: sleepwalker.trainer.MultiLabelTrainer.MultiLabelTrainer.normalize_task_config
    task_config:
      sleep:
        labels: [wake, n1, n2, n3, rem]
        default: null
        target_resolution: 30s
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse-log
      arousal:
        labels: [arousal, no arousal]
        default: no arousal
        target_resolution: 1s
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse-log
      breathing:
        labels: [apnea, hypopnea, regular breathing]
        default: regular breathing
        target_resolution: 5s
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse-log
      desaturation:
        labels: [desaturation, no desaturation]
        default: no desaturation
        target_resolution: 10s
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse-log
  condition_task: sleep
  condition_labels: [n1, n2, n3, rem]
  conditioned_tasks: [arousal, breathing, desaturation]
  device: cuda:1
  warmup_device: cpu
  save_every: 1
  early_stopping: 8
  log_batches: false
run:
  experiment_name: paper_monolithic_hsp_full
  model_name: sleeptransformer-utime
  batch_size: 32
  n_samples: 100000
  num_workers_dataloader: 4
  test_repeats: [1]
  use_mlflow: false
  log_path: results/hsp_expert_suite/full/monolithic
  tags:
    task: multitask
    dataset: hsp
    baseline: monolithic
  expert_task: multitask
