"""Prediction-package export and loading for Sleepwalker models.

This module packages a trained model together with a trainer and an
unlabelled-dataset template so inference can later be run without reconstructing
the original training script. Tests in ``tests/test_deployment.py`` cover the
main round-trip behavior and the current ``.swmodel`` file format.
"""

from __future__ import annotations

import copy
import io
import json
import os
import platform
import subprocess
import sys
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Optional

import cloudpickle
import numpy as np
import pandas as pd
import torch

from sleepwalker.datasets.Basedataset import batch_collate
from sleepwalker.datasets.UnlabelledDataset import UnlabelledDataset


def _safe_git_commit() -> Optional[str]:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except Exception:
        return None


def _normalize_device_string(device: str | torch.device) -> str:
    return str(device)


def _torch_save_bytes(obj: Any) -> bytes:
    buf = io.BytesIO()
    torch.save(obj, buf)
    return buf.getvalue()


def _sanitize_trainer_for_export(trainer):
    trainer_copy = copy.copy(trainer)
    if hasattr(trainer_copy, "device"):
        trainer_copy.device = "cpu"
    if hasattr(trainer_copy, "warmup_device"):
        trainer_copy.warmup_device = "cpu"
    for attr in [
        "optimizer_fn",
        "lr_scheduler_fn",
        "loss_function",
        "base_loss_function",
        "train_transform",
        "task_loss_functions",
        "domain_head",
    ]:
        if hasattr(trainer_copy, attr):
            value = {} if attr == "task_loss_functions" else None
            setattr(trainer_copy, attr, value)
    return trainer_copy


def _model_copy_for_export(model):
    return copy.deepcopy(model).to("cpu")


def _normalize_export_path(path: str) -> str:
    normalized = os.fspath(path)
    if normalized.endswith(os.sep):
        raise ValueError("Prediction package export path must be a file path, not a directory path.")
    root, ext = os.path.splitext(normalized)
    if ext != ".swmodel":
        return normalized + ".swmodel"
    else:
        return normalized

def _to_unlabelled_dataset(dataset):
    if isinstance(dataset, UnlabelledDataset):
        return dataset.clone()
    if hasattr(dataset, "to_unlabelled"):
        return dataset.to_unlabelled()
    raise ValueError(
        f"Dataset of type {type(dataset).__name__} does not support export to an UnlabelledDataset."
    )


@dataclass
class PredictionPackage:
    """In-memory representation of an exported prediction package.

    Attributes:
        model: Loaded model instance with weights restored.
        trainer: Loaded trainer instance configured for inference.
        unlabelled_dataset: Dataset template used to initialize EDF files at
            prediction time.
        metadata: Export metadata loaded from ``meta.json``.
    """

    model: Any
    trainer: Any
    unlabelled_dataset: Any
    metadata: dict[str, Any]

    def predict_window(self, batch, n_repeat: int = 1) -> pd.DataFrame:
        """Run inference for one already-collated batch."""
        return self.trainer.predict_window(self.model, batch, n_repeat=n_repeat)

    def predict_loader(self, loader) -> pd.DataFrame:
        """Run inference for all batches produced by a loader."""
        return self.trainer.predict_loader(self.model, loader)

    def predict_patient(
        self,
        edf_path,
        batch_size: int,
        num_workers_dataset: int = 1,
        num_workers_loader: int = 0,
        collate_fn=None,
    ) -> pd.DataFrame:
        """Predict one EDF file using the embedded dataset template.

        Args:
            edf_path: EDF file to score.
            batch_size: Inference batch size.
            num_workers_dataset: Worker count used while preparing the
                temporary dataset instance.
            num_workers_loader: Dataloader worker count.
            collate_fn: Optional collate function. Defaults to
                :func:`sleepwalker.datasets.Basedataset.batch_collate`.

        Returns:
            A prediction DataFrame generated by the embedded trainer.
        """
        return self.trainer.predict_patient(
            self.model,
            self.unlabelled_dataset,
            edf_path,
            batch_size=batch_size,
            num_workers_dataset=num_workers_dataset,
            num_workers_loader=num_workers_loader,
            collate_fn=batch_collate if collate_fn is None else collate_fn,
        )


def export_prediction_package(
    path: str,
    *,
    model,
    trainer,
    dataset,
    model_card_md: str = "",
    metadata: Optional[dict[str, Any]] = None,
) -> PredictionPackage:
    """Export a trained model, trainer, and dataset template to `.swmodel`.

    Args:
        path: Output file path. The ``.swmodel`` suffix is appended when
            missing.
        model: Trained model instance.
        trainer: Trainer instance. Export sanitizes trainer state that is only
            needed for training.
        dataset: Labelled or unlabelled dataset object. It must either already
            be an ``UnlabelledDataset`` or provide ``to_unlabelled()``.
        model_card_md: Optional Markdown stored as ``model_card.md`` in the
            package.
        metadata: Optional metadata merged into the exported manifest.

    Returns:
        A :class:`PredictionPackage` representing the exported contents.

    Raises:
        ValueError: If the export path refers to a directory or the dataset
            cannot be converted into an unlabelled template.

    Notes:
        The current on-disk format stores both a serialized model object and a
        separate ``state_dict``. Tests confirm round-tripping of trainer and
        dataset template metadata, but long-term compatibility guarantees are
        not established.
    """
    path = _normalize_export_path(path)
    unlabelled_dataset = _to_unlabelled_dataset(dataset)
    model_export = _model_copy_for_export(model)
    trainer_export = _sanitize_trainer_for_export(trainer)
    package_metadata = {
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "git_commit": _safe_git_commit(),
        "python_version": sys.version,
        "platform": platform.platform(),
        "torch_version": torch.__version__,
        "numpy_version": np.__version__,
        "pandas_version": pd.__version__,
        "model_class": f"{model.__class__.__module__}.{model.__class__.__name__}",
        "trainer_class": f"{trainer.__class__.__module__}.{trainer.__class__.__name__}",
        "source_dataset_class": f"{dataset.__class__.__module__}.{dataset.__class__.__name__}",
        "unlabelled_dataset_class": f"{unlabelled_dataset.__class__.__module__}.{unlabelled_dataset.__class__.__name__}",
        "source_event_mapping": dict(getattr(dataset, "event_mapping", {}) or {}),
    }
    if metadata is not None:
        package_metadata.update(metadata)
    package_metadata["format"] = "sleepwalker-swmodel-v1"

    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("meta.json", json.dumps(package_metadata, indent=2, ensure_ascii=True))
        zf.writestr("model_card.md", model_card_md)
        zf.writestr("model.pt", _torch_save_bytes(model.state_dict()))
        zf.writestr("model.pkl", cloudpickle.dumps(model_export))
        zf.writestr("trainer.pkl", cloudpickle.dumps(trainer_export))
        zf.writestr("unlabelled_dataset.pkl", cloudpickle.dumps(unlabelled_dataset))

    return PredictionPackage(
        model=model,
        trainer=trainer,
        unlabelled_dataset=unlabelled_dataset,
        metadata=package_metadata,
    )


def load_prediction_package(path: str, map_location: str | torch.device = "cpu") -> PredictionPackage:
    """Load a previously exported prediction package.

    Args:
        path: Path to a ``.swmodel`` zip file or an unpacked package directory.
        map_location: Torch device used to restore the model weights.

    Returns:
        A :class:`PredictionPackage` with trainer device fields rewritten to
        the requested ``map_location`` when those attributes exist.
    """
    if os.path.isdir(path):
        with open(os.path.join(path, "model.pkl"), "rb") as f:
            model = cloudpickle.load(f)
        with open(os.path.join(path, "trainer.pkl"), "rb") as f:
            trainer = cloudpickle.load(f)
        with open(os.path.join(path, "unlabelled_dataset.pkl"), "rb") as f:
            unlabelled_dataset = cloudpickle.load(f)
        with open(os.path.join(path, "meta.json"), "r", encoding="utf-8") as f:
            metadata = json.load(f)
        state_dict = torch.load(os.path.join(path, "model.pt"), map_location=map_location)
    else:
        with zipfile.ZipFile(path, "r") as zf:
            model = cloudpickle.loads(zf.read("model.pkl"))
            trainer = cloudpickle.loads(zf.read("trainer.pkl"))
            unlabelled_dataset = cloudpickle.loads(zf.read("unlabelled_dataset.pkl"))
            metadata = json.loads(zf.read("meta.json").decode("utf-8"))
            state_dict = torch.load(io.BytesIO(zf.read("model.pt")), map_location=map_location)
    model.load_state_dict(state_dict)
    model = model.to(map_location)
    device_str = _normalize_device_string(map_location)
    if hasattr(trainer, "device"):
        trainer.device = device_str
    if hasattr(trainer, "warmup_device"):
        trainer.warmup_device = device_str
    return PredictionPackage(
        model=model,
        trainer=trainer,
        unlabelled_dataset=unlabelled_dataset,
        metadata=metadata,
    )
