root: /raid/sleepwalker/hsp
task: arousal
batch_size: 128
epochs: 2
n_samples: 10000
num_workers_dataset: 2
num_workers_dataloader: 8
sample_frequency: 100
target_resolution: "1s"
stride: "1s"
grouped: true
scaler: true
clean: true
arousal_weight: 10
balance_batches: false
balance_gamma: 0.75
channels:
  - eeg
  - eog
  - chin_emg
model: utime-big
total_input: "60s"
val_frac: 0.1
dry: false
use_mlflow: true
max_edf_files: null
patient_limit: null
annotated_only: true
require_positive_labels: true
