train_root: /raid/sleepwalker/ruhrlandklinik/raw/train-test-2023
test_root: /raid/sleepwalker/ruhrlandklinik/raw/val-2024
batch_size: 128
epochs: 2
n_samples: 10000
num_workers_dataset: 8
num_workers_dataloader: 8
sample_frequency: 100
target_resolution: "1s"
stride: "1s"
grouped: true
scaler: true
clean: true
arousal_weight: 10
channels:
  - eeg
  - eog
  - chin_emg
  - ECG
model: utime-big
total_input: "60s"
val_frac: 0.1
dry: false
use_mlflow: true
