root: /raid/sleepwalker/hsp
task: desaturation
batch_size: 16
epochs: 2
n_samples: 512
num_workers_dataset: 2
num_workers_dataloader: 0
sample_frequency: 100
target_resolution: "10s"
stride: "2s"
grouped: true
scaler: true
sleep_percentage: 0.5
class_weights:
  desaturation: 2.0
  no desaturation: 1.0
channels:
  - spo2
model: utime-big
total_input: "100s"
val_frac: 0.1
test_frac: 0.0
dry: true
use_mlflow: false
max_edf_files: 500
patient_limit: 40
annotated_only: true
balance_batches: false
balance_gamma: 0.75
