seed: 17
data:
  name: sleepwalker.datasets.HSP.HSP
  channels:
    - logical_name: EEG
      physical_names: [C3-M2, C4-M1, F3-M2, F4-M1, O1-M2, O2-M1, CZ-M2, CZ-M1, C3-M1, C4-M2, F3-M1, F4-M2, O1-M1, O2-M2]
      normalizer: &eeg_normalizer
        name: sleepwalker.datasets.normalizer.EEGFilterNormalizer.EEGFilterNormalizer
        fs: 100
      unit: uV
    - logical_name: EOG
      physical_names: [E1-M2, E2-M1, E2-M2, E1, E2, Eye Up, Eye Down]
      normalizer: *eeg_normalizer
      unit: uV
    - logical_name: Chin EMG
      physical_names: [CHIN1-CHIN2, Chin1-Chin2, CHIN1-CHIN3, Chin1-Chin3, CHIN2-CHIN3, Chin2-Chin3, Chin3-Chin2, Chin3, Chin2, CHIN1, CHIN2, CHIN3, CHIN, CHINz, EMG]
      unit: uV
    - logical_name: EKG
      physical_names: [EKG]
      unit: uV
  sample_frequency: 100
  event_mapping:
    arousal: arousal
    n1: sleep
    n2: sleep
    n3: sleep
    rem: sleep
  total_input: 60s

  stride: 1s
  output_classes: [no_arousal, arousal]
  prepare_patient:
    name: sleepwalker.training.callbacks.trim_patient_to_events
    keep_events: [sleep]
  prepare_target:
    name: sleepwalker.trainer.utils.targets.prepare_multiclass_target
    target_resolution: 1s
    target_classes: [no_arousal, arousal]
  patient_filter:
    - name: sleepwalker.training.files.filter_edf_files
    - name: sleepwalker.datasets.HSP.filter_hsp_annotation_labels
      required_labels: [arousal]
  files:
    train:
      name: sleepwalker.datasets.HSP.get_annotated_hsp_edf_files
      root: /raid/sleepwalker/hsp
    validation_fraction: 0.1
    test_fraction: 0.1
  label: HSP
  num_workers: 2
model:
  name: sleepwalker.models.UTime.UTime
  sampling_frequency: 0.01s
  channel: [64, 128, 128, 256]
  kernel: [5, 5, 3, 3]
  maxpool: [5, 5, 3, 3]
  norm: channel
  activation: elu
  mlp_size: 512
  dropout_p: 0
  preprocessors:
    - name: sleepwalker.training.callbacks.robust_scaler
      skip_first: 1
trainer:
  target_resolution: 1s
  name: sleepwalker.trainer.MulticlassTrainer.MulticlassTrainer
  epochs: 20
  optimizer:
    name: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0001
  lr_scheduler:
    name: torch.optim.lr_scheduler.LinearLR
    start_factor: 1
    end_factor: 0.01
    total_iters: 50
  loss_function: torch.nn.functional.cross_entropy
  save_every: 10
  balance_batches: false
  balance_gamma: 0.75
  class_weights:
    no_arousal: 1
    arousal: 10
run:
  experiment_name: arousal_hsp
  batch_size: 128
  n_samples: 250000
  num_workers_dataloader: 8
  test_repeats: [1, 2]
  use_mlflow: true
  log_path: results/arousal
  tags:
    task: arousal
    dataset: hsp
    model: UTime
  expert_task: arousal
