seed: 17
data:
  name: sleepwalker.datasets.Ruhrlandklinik.Ruhrlandklinik
  channels:
    - logical_name: RIP Flow
      physical_names: [RIP Flow]
      normalizer: &respiration_normalizer
        name: sleepwalker.datasets.normalizer.RespirationFilterNormalizer.RespirationFilterNormalizer
        fs: 25
      unit: V/s
    - logical_name: RIP Sum
      physical_names: [RIP Sum]
      normalizer: *respiration_normalizer
      unit: V
    - logical_name: Chest
      physical_names: [Chest]
      normalizer: *respiration_normalizer
      unit: V
    - logical_name: Abdomen
      physical_names: [Abdomen]
      normalizer: *respiration_normalizer
      unit: V
    - logical_name: Saturation
      physical_names: [Saturation]
      normalizer:
        name: sleepwalker.datasets.normalizer.SaturationFilterNormalizer.SaturationFilterNormalizer
        fs: 25
      unit: '%'
  sample_frequency: 25
  event_mapping:
    entsättigung: desaturation
    wach: wake
    n1: sleep
    n2: sleep
    n3: sleep
    rem: sleep
    a. gemischt: apnea
    a. obstruktiv: apnea
    a. zentral: apnea
    apnoe: apnea
    h. obstruktiv: hypopnea
    h. zentral: hypopnea
    hypopnea-gemischt: hypopnea
    hypopnoe: hypopnea
  total_input: 60s
  target_resolution: 5s
  stride: 1s
  output_classes: [apnea, hypopnea, regular breathing]
  prepare_patient:
    name: sleepwalker.training.breathing.prepare_patient
    min_desaturation_sleep_overlap_seconds: 1
  prepare_target:
    name: sleepwalker.trainer.utils.targets.prepare_multiclass_target
    target_classes: [apnea, hypopnea, regular breathing]
    filters:
      - columns: [desaturation]
        percentage: 0.5
        mode: min
      - columns: [sleep]
        percentage: 0.5
        mode: min
  files:
    train:
      name: sleepwalker.training.files.select_edf_files
      root: /raid/sleepwalker/ruhrlandklinik/raw/train-test-2023
      include_pap: false
    validation_fraction: 0.1
    test:
      name: sleepwalker.training.files.select_edf_files
      root: /raid/sleepwalker/ruhrlandklinik/raw/val-2024
      include_pap: false
  label: Ruhrland2024
  num_workers: 8
model:
  name: sleepwalker.models.UTime.UTime
  sampling_frequency: 0.04s
  channel: [64, 128, 128, 256]
  kernel: [5, 5, 3, 3]
  maxpool: [5, 5, 3, 3]
  norm: channel
  activation: elu
  mlp_size: 512
  dropout_p: 0
  preprocessors:
    - name: sleepwalker.models.preprocessors.RobustScaler.RobustScaler
      lower_quantile: 0.1
      upper_quantile: 0.9
trainer:
  name: sleepwalker.trainer.MulticlassTrainer.MulticlassTrainer
  epochs: 50
  optimizer:
    name: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0001
  lr_scheduler:
    name: torch.optim.lr_scheduler.LinearLR
    start_factor: 1
    end_factor: 0.01
    total_iters: 50
  loss_function: torch.nn.functional.cross_entropy
  save_every: 10
  balance_batches: false
  balance_gamma: 0.75
  class_weights:
    apnea: 1
    hypopnea: 1
    regular breathing: 1
run:
  experiment_name: breathing
  batch_size: 64
  n_samples: 100000
  num_workers_dataloader: 8
  test_repeats: [1]
  use_mlflow: true
  log_path: results/breathing
  tags:
    task: breathing
    dataset: ruhrland
    model: UTime
  expert_task: breathing
