seed: 17
data:
  name: sleepwalker.datasets.HSP.HSP
  channels:
    - logical_name: Abdomen
      physical_names: [ABD, ABDOMEN, Abdomen]
      normalizer: &respiration_normalizer
        name: sleepwalker.datasets.normalizer.RespirationFilterNormalizer.RespirationFilterNormalizer
        fs: 100
      unit: uV
    - logical_name: Chest
      physical_names: [CHEST, THORAX, Chest]
      normalizer: *respiration_normalizer
      unit: uV
    - logical_name: Airflow
      physical_names: [PTAF, AIRFLOW, AirFlow, Airflow2, IC, THERMISTOR, Thermistor, Flow, Flow_DR, CFLOW, CFlow, C-Flow, XFlow]
      normalizer: *respiration_normalizer
      unit: uV
    - logical_name: SpO2
      physical_names: [SaO2, SpO2, SPO2]
      normalizer:
        name: sleepwalker.datasets.normalizer.SaturationFilterNormalizer.SaturationFilterNormalizer
        fs: 100
      unit: '%'
  sample_frequency: 100
  event_mapping:
    n1: sleep
    n2: sleep
    n3: sleep
    rem: sleep
    apnea: apnea
    obstructive-apnea: apnea
    central-apnea: apnea
    mixed-apnea: apnea
    hypopnea: hypopnea
  total_input: 60s

  stride: 1s
  output_classes: [apnea, hypopnea, regular breathing]
  prepare_patient:
    name: sleepwalker.training.callbacks.trim_patient_to_events
    keep_events: [sleep]
  prepare_target:
    name: sleepwalker.trainer.utils.targets.prepare_multiclass_target
    target_resolution: 5s
    target_classes: [apnea, hypopnea, regular breathing]
    filters:
      - columns: [sleep]
        percentage: 0.5
        mode: min
  prepare_sample:
    name: sleepwalker.training.callbacks.prepare_tensor_sample
    max_nan_fraction: 0.05
  patient_filter:
    name: sleepwalker.training.files.filter_edf_files
  files:
    train:
      name: sleepwalker.datasets.HSP.get_annotated_hsp_edf_files
      root: /raid/sleepwalker/hsp
    validation_fraction: 0.1
    test_fraction: 0.1
  label: HSP
  num_workers: 2
model:
  name: sleepwalker.models.UTime.UTime
  sampling_frequency: 0.01s
  channel: [64, 128, 128, 256]
  kernel: [5, 5, 3, 3]
  maxpool: [5, 5, 3, 3]
  norm: channel
  activation: elu
  mlp_size: 512
  dropout_p: 0
  preprocessors:
    - name: sleepwalker.models.preprocessors.RobustScaler.RobustScaler
      lower_quantile: 0.1
      upper_quantile: 0.9
trainer:
  target_resolution: 5s
  name: sleepwalker.trainer.MulticlassTrainer.MulticlassTrainer
  epochs: 20
  optimizer:
    name: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0001
  lr_scheduler:
    name: torch.optim.lr_scheduler.LinearLR
    start_factor: 1
    end_factor: 0.01
    total_iters: 50
  loss_function: torch.nn.functional.cross_entropy
  save_every: 10
  class_weights:
    apnea: 2
    hypopnea: 2
    regular breathing: 1
run:
  experiment_name: breathing_hsp
  batch_size: 128
  n_samples: 250000
  num_workers_dataloader: 8
  test_repeats: [1]
  use_mlflow: true
  log_path: results/breathing
  tags:
    task: breathing
    dataset: hsp
    model: UTime
  expert_task: breathing
