seed: 17
data:
  name: sleepwalker.datasets.Ruhrlandklinik.Ruhrlandklinik
  channels:
    - logical_name: EEG
      physical_names: [C3-M2, C4-M1, F3-M2, F4-M1, O1-M2, O2-M1]
      normalizer:
        name: sleepwalker.datasets.normalizer.EEGFilterNormalizer.EEGFilterNormalizer
        fs: 100
      quality_name:
        C3-M2: C3 Impedanz
        C4-M1: C4 Impedanz
        F3-M2: F3 Impedanz
        F4-M1: F4 Impedanz
        O1-M2: O1 Impedanz
        O2-M1: O2 Impedanz
      unit: V
    - logical_name: Chest
      physical_names: [Chest]
      normalizer: &respiration_normalizer
        name: sleepwalker.datasets.normalizer.RespirationFilterNormalizer.RespirationFilterNormalizer
        fs: 100
      unit: V
    - logical_name: Abdomen
      physical_names: [Abdomen]
      normalizer: *respiration_normalizer
      unit: V
    - logical_name: Saturation
      physical_names: [Saturation]
      normalizer:
        name: sleepwalker.datasets.normalizer.SaturationFilterNormalizer.SaturationFilterNormalizer
        fs: 100
        clip_range: null
      unit: '%'
    - logical_name: Pulse Waveform
      physical_names: [Pulse Waveform]
      normalizer:
        name: sleepwalker.datasets.normalizer.PulseFilterNormalizer.PulseFilterNormalizer
        fs: 100
  sample_frequency: 100
  event_mapping:
    wach: wake
    n1: n1
    n2: n2
    n3: n3
    rem: rem
    a. gemischt: obstruction
    a. obstruktiv: obstruction
    a. zentral: obstruction
    apnoe: obstruction
    cheyne stokes: obstruction
    fg apnoe geschlossen: obstruction
    fg apnoe geöffnet: obstruction
    fg-apnoe unbekannt: obstruction
    h. obstruktiv: obstruction
    h. zentral: obstruction
    fg hypopnoe: obstruction
    hypopnea-gemischt: obstruction
    hypopnoe: obstruction
    arousal: arousal
    plm-arousal: arousal
    rera: arousal
    entsättigung: desaturation
  total_input: 630s
  target_resolution: 30s
  prepare_patient:
    name: sleepwalker.training.callbacks.trim_patient_to_events
  prepare_target:
    name: sleepwalker.trainer.MultiLabelTrainer.MultiLabelTrainer.prepare_target
    task_config: &task_config
      breathing:
        labels: [obstruction, regular]
        default: regular
        percentage: 0.5
        target_resolution: 10s
        sequence_len: 3
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse
      arousal:
        labels: [arousal, no arousal]
        default: no arousal
        percentage: 0.5
        target_resolution: 1s
        sequence_len: 30
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse
      desat:
        labels: [desaturation, no desaturation]
        default: no desaturation
        percentage: 0.5
        target_resolution: 10s
        sequence_len: 3
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse
      sleep:
        labels: [n1, n2, n3, rem, wake]
        default: null
        percentage: 0.5
        target_resolution: 30s
        sequence_len: 1
        loss_function: torch.nn.functional.cross_entropy
        loss_mode: inverse
  prepare_sample:
    name: sleepwalker.training.callbacks.prepare_tensor_sample
    max_nan_fraction: 0.05
    quality_max_mean:
      EEG: 20000
    valid_ranges:
      Saturation: [-5, 5]
    max_out_of_range_fraction: 0.05
    min_std:
      EEG: 0.001
      Chest: 0.001
      Abdomen: 0.001
      Pulse Waveform: 0.001
  files:
    train:
      name: sleepwalker.training.multilabel.select_files
      root: /raid/sleepwalker/ruhrlandklinik/raw/train-test-2023
      training: true
      include_pap: true
      quantile: 0.05
      num_workers: 8
    test:
      name: sleepwalker.training.multilabel.select_files
      root: /raid/sleepwalker/ruhrlandklinik/raw/val-2024
      training: false
      include_pap: true
  label: Ruhrland2024
  num_workers: 8
model:
  name: sleepwalker.models.CompositeModel.CompositeModel
  task_config: *task_config
  models:
    - name: sleepwalker.models.CompositeModel.CompositeModelEntry
      input_channels: [EEG, Chest, Abdomen, Saturation, Pulse Waveform]
      model:
        name: sleepwalker.models.UTime.UTime
        classes: null
        sampling_frequency: 0.01s
        channel: [16, 32, 64, 128]
        maxpool: [10, 8, 6, 4]
        kernel: [5, 5, 5, 5]
        norm: channel
        mlp_size: 64
trainer:
  name: sleepwalker.trainer.MultiLabelTrainer.MultiLabelTrainer
  epochs: 100
  optimizer:
    name: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0001
  lr_scheduler:
    name: torch.optim.lr_scheduler.LinearLR
    start_factor: 1
    end_factor: 0.01
    total_iters: 50
  task_config: *task_config
  condition_task: sleep
  condition_labels: [n1, n2, n3, rem]
  conditioned_tasks: [breathing, arousal, desat]
  save_every: 10
  log_batches: false
run:
  experiment_name: ruhrland_metamodel_multilabel_monolithic
  model_name: monolithic
  batch_size: 128
  n_samples: null
  num_workers_dataloader: 8
  use_mlflow: true
  log_path: results/multilabel
  tags:
    task: multilabel
    fusion: monolithic
  expert_task: multilabel
