seed: 17
data:
  - name: sleepwalker.datasets.SleepEDFx.SleepEDFx
    channels:
      - logical_name: EEG Fpz-Cz
        physical_names: [EEG Fpz-Cz]
        normalizer:
          name: sleepwalker.datasets.normalizer.EEGFilterNormalizer.EEGFilterNormalizer
          fs: 100
        unit: uV
    sample_frequency: 100
    event_mapping:
      sleep stage w: wake
      sleep stage 1: n1
      sleep stage 2: n2
      sleep stage 3: n3
      sleep stage 4: n3
      sleep stage r: rem
    total_input: 30s
    target_resolution: 30s
    stride: 30s
    assume_units_if_missing: false
    output_classes: [wake, n1, n2, n3, rem]
    prepare_patient:
      name: sleepwalker.training.callbacks.trim_patient_to_events
      keep_events: [n1, n2, n3, rem]
    prepare_target:
      name: sleepwalker.trainer.utils.targets.prepare_multiclass_target
      target_classes: [wake, n1, n2, n3, rem]
    patient_filter:
      name: sleepwalker.training.files.filter_edf_files
    files:
      train:
        name: sleepwalker.datasets.utils.get_edf_files_in_repo
        root: /raid/sleepwalker/sleep-edfx
      validation_fraction: 0.1
      test_fraction: 0.3
    label: sleepedfx
    num_workers: 8
model:
  name: sleepwalker.models.AttnSleep.AttnSleep
trainer:
  name: sleepwalker.trainer.MulticlassTrainer.MulticlassTrainer
  epochs: 100
  optimizer:
    name: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.001
    amsgrad: true
  lr_scheduler:
    name: torch.optim.lr_scheduler.LinearLR
    start_factor: 1
    end_factor: 0.01
    total_iters: 50
  loss_function: torch.nn.functional.cross_entropy
  save_every: 1
  early_stopping: 15
  loss_mode: inverse-log
  class_weights:
    wake: 1.5
    n1: 2
    n2: 1.5
    n3: 1
    rem: 1.5
run:
  experiment_name: sleep_attnsleep
  model_name: attnsleep
  batch_size: 128
  n_samples: 250000
  num_workers_dataloader: 8
  test_repeats: [1]
  use_mlflow: true
  log_path: results/sleep
  tags:
    task: sleep
    model: attnsleep
  expert_task: sleep
